"""
db_connect.py — Minimal, read-only Postgres query runner for racadm/configadm/prcadm.

Usage:
    python db_connect.py --db racadm "SELECT * FROM racadm.inventory WHERE inventory_number = '9999222795867'"
    python db_connect.py --db racadm --file my_query.sql

Connection details are read from the .env file at the project root (never hardcode
credentials in this script or pass them on the command line).

racadm, configadm, and prcadm are frequently separate database CLUSTERS (different
host/port/credentials), not just different database names on the same server. Each
schema therefore supports its own optional connection override, falling back to the
generic DB_* values when not set:

    Generic (fallback) values:
        DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_SSLMODE

    Per-schema overrides (all optional; only set the ones that differ from the
    generic values above):
        RACADM_DB_HOST, RACADM_DB_PORT, RACADM_DB_USER, RACADM_DB_PASSWORD, RACADM_DB_SSLMODE
        RACADM_DB_NAME     (defaults to "racdb")

        CONFIGADM_DB_HOST, CONFIGADM_DB_PORT, CONFIGADM_DB_USER, CONFIGADM_DB_PASSWORD, CONFIGADM_DB_SSLMODE
        CONFIGADM_DB_NAME  (defaults to "configdb")

        PRCADM_DB_HOST, PRCADM_DB_PORT, PRCADM_DB_USER, PRCADM_DB_PASSWORD, PRCADM_DB_SSLMODE
        PRCADM_DB_NAME     (defaults to "prcdb")

Safety:
    - Only SELECT / WITH statements are allowed (read-only investigation tool).
    - Connections are opened read-only at the session level as a second guard.
"""

import argparse
import os
import sys
from pathlib import Path

import psycopg2
from dotenv import load_dotenv
from tabulate import tabulate

PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(PROJECT_ROOT / ".env")

DB_NAME_BY_SCHEMA = {
    "racadm": os.getenv("RACADM_DB_NAME", "racdb"),
    "configadm": os.getenv("CONFIGADM_DB_NAME", "configdb"),
    "prcadm": os.getenv("PRCADM_DB_NAME", "prcdb"),
}


def _schema_env(schema: str, suffix: str):
    """Look up a per-schema override (e.g. CONFIGADM_DB_HOST), falling back to
    the generic DB_<suffix> value when the schema-specific one isn't set."""
    return os.getenv(f"{schema.upper()}_DB_{suffix}") or os.getenv(f"DB_{suffix}")


def get_connection(schema: str):
    dbname = DB_NAME_BY_SCHEMA.get(schema)
    if not dbname:
        raise ValueError(f"Unknown schema '{schema}'. Expected one of: {list(DB_NAME_BY_SCHEMA)}")

    host = _schema_env(schema, "HOST")
    user = _schema_env(schema, "USER")
    if not host or not user:
        raise EnvironmentError(
            f"Missing connection details for schema '{schema}'. Set either the generic "
            f"DB_HOST/DB_USER or the schema-specific {schema.upper()}_DB_HOST/{schema.upper()}_DB_USER "
            "in the .env file at the project root (do not paste secrets in chat)."
        )

    connect_kwargs = dict(
        host=host,
        port=_schema_env(schema, "PORT") or "5432",
        dbname=dbname,
        user=user,
        sslmode=_schema_env(schema, "SSLMODE") or "require",
        connect_timeout=10,
    )
    # Password is optional (e.g. trust/peer auth or local dev Postgres with no password).
    db_password = _schema_env(schema, "PASSWORD")
    if db_password:
        connect_kwargs["password"] = db_password

    conn = psycopg2.connect(**connect_kwargs)
    # Enforce read-only at the session level regardless of the query text.
    conn.set_session(readonly=True, autocommit=True)
    return conn


def assert_read_only(sql: str):
    # Strip SQL line comments ("-- ...") and block comments ("/* ... */") before
    # checking the leading keyword, so files starting with a header comment
    # (as generated by /Save-Query) aren't misclassified as non-SELECT.
    without_line_comments = "\n".join(
        line for line in sql.splitlines() if not line.strip().startswith("--")
    )
    import re as _re
    without_comments = _re.sub(r"/\*.*?\*/", "", without_line_comments, flags=_re.DOTALL)

    stripped = without_comments.strip().lstrip("(").strip()
    first_word = stripped.split(None, 1)[0].lower() if stripped else ""
    if first_word not in ("select", "with"):
        raise ValueError("Refusing to run a non-SELECT statement. This tool is strictly read-only.")


def run_query(schema: str, sql: str):
    assert_read_only(sql)
    conn = get_connection(schema)
    try:
        with conn.cursor() as cur:
            cur.execute(sql)
            if cur.description is None:
                print("Query executed. No rows returned.")
                return
            columns = [desc[0] for desc in cur.description]
            rows = cur.fetchall()
            print(tabulate(rows, headers=columns, tablefmt="github"))
            print(f"\n({len(rows)} rows)")
    finally:
        conn.close()


def main():
    parser = argparse.ArgumentParser(description="Run a read-only SQL query against racadm/configadm/prcadm.")
    parser.add_argument("--db", required=True, choices=list(DB_NAME_BY_SCHEMA), help="Schema/database to query")
    parser.add_argument("--file", help="Path to a .sql file containing the query")
    parser.add_argument("query", nargs="?", help="Inline SQL query (alternative to --file)")
    args = parser.parse_args()

    if args.file:
        sql = Path(args.file).read_text(encoding="utf-8")
    elif args.query:
        sql = args.query
    else:
        parser.error("Provide either a query string or --file <path>.")
        return

    try:
        run_query(args.db, sql)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
